# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none 

pool: 
  vmImage: 'ubuntu-latest' #ubuntu-latest #macOS-latest

variables:
  - name: brancheslinux
    value: (feature/.*|master)
  - name: brancheswindows
    value: (feature/.+|master)$
  - name: targetbranch
    value:  develop 

stages:
- stage: checkifcontinue
  jobs:
  - job: validate
    steps:
    - script: |
        echo "Target branch: $(System.PullRequest.TargetBranch)"
        echo "Source branch: $(System.PullRequest.SourceBranch)"
      displayName: 'show target branch'
      condition: eq(variables['Build.Reason'], 'PullRequest') 
      
    - script: |
        echo "Source branch: $(System.PullRequest.SourceBranch)"
        if [[ "$(System.PullRequest.SourceBranch)" =~ ^refs/heads/$(brancheslinux)$ ]]; then
          echo "Allowed branch"
        else
          echo "Only $(brancheslinux) can be merged into $(targetbranch)"
          exit 1
        fi
      condition: and(eq(variables['Agent.OS'], 'Linux'),eq(variables['Build.Reason'], 'PullRequest') )
      displayName: 'check if allowed when linux'